
cache: bundler
language: ruby
before_install:
  - gem update --remote bundler
  - gem update --system
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.13.7
install:
  - bundle install --retry=3
script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
